package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BaseArticleType;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class ArticleType extends BaseArticleType<ArticleType> {
	public static final ArticleType dao = new ArticleType().dao();
}
