package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BaseFriend;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Friend extends BaseFriend<Friend> {
	public static final Friend dao = new Friend().dao();
}
