package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BaseFriendLink;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FriendLink extends BaseFriendLink<FriendLink> {
	public static final FriendLink dao = new FriendLink().dao();
}
