package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BasePostsComment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PostsComment extends BasePostsComment<PostsComment> {
	public static final PostsComment dao = new PostsComment().dao();
}
