package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BaseTags;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Tags extends BaseTags<Tags> {
	public static final Tags dao = new Tags().dao();
}
