package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BaseUploadCounter;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UploadCounter extends BaseUploadCounter<UploadCounter> {
	public static final UploadCounter dao = new UploadCounter().dao();
}
