package com.szx.bbs.common.model;

import com.szx.bbs.common.model.base.BaseUsersOpenOauth;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class UsersOpenOauth extends BaseUsersOpenOauth<UsersOpenOauth> {
	public static final UsersOpenOauth dao = new UsersOpenOauth().dao();
}
